version: 1

sources:
  - name: sdsc_bootcamp_data
    description: "SDSC raw data (loaded from raw files)"
    schema: sdsc_bootcamp_data
    database: carto-ps-bq-developers
    tables:
      - name: raw_public_transportation
        identifier: osm_public_transport_usa
        description: "OpenStreetMap public transportation stops US"
        columns:
          - name: geoid
            description: "GEOID"
            data_type: string
          - name: latitude
            description: "latitude"
            data_type: float64
          - name: longitude
            description: "latitude"
            data_type: float64
          - name: do_date
            description: "DO_DATE"
            data_type: string
          - name: version
            description: "VERSION"
            data_type: string
          - name: amenity
            description: "AMENITY"
            data_type: string
          - name: public_transport
            description: "PUBLIC_TRANSPORT"
            data_type: string
          - name: tags_key
            description: "TAGS_KEY"
            data_type: string
          - name: tags_value
            description: "TAGS_VALUE"
            data_type: string
          - name: country_iso2
            description: "COUNTRY_ISO2"
            data_type: string
